### ISSUE TITLE
Installation fails: "can't access lexical declaration `metaParser' before initialization"

### ISSUE THREAD

**Issue by terminalmage** [aalvarado/JiraDarkTheme#12]
Full error:

```
Stylus failed to parse usercss:

can't access lexical declaration `metaParser' before initialization
```

**Comment by terminalmage** [comment]
And now I'm getting the error `invalid regexp group` instead.

**Comment by aalvarado** [comment]
this goes without saying but, maybe you want to try the newest firefox?

**Comment by terminalmage** [comment]
Not an option right now.

**Comment by terminalmage** [comment]
Feel free to close if this is not able to be replicated on newer Firefox versions. I can rely on Dark Reader in the meantime.

**Comment by terminalmage** [comment]
I was able to get someone else to test on newer Firefox and it worked. Assuming then that this is a WONTFIX, and closing.

**Comment by aalvarado** [comment]
Awesome, thanks for checking and taking the time. I assume that the issue is with the extension and that version of firefox rather than this simple css file
