### ISSUE TITLE
Contrast issues with sub-task

### ISSUE THREAD

**Issue by SubhrajyotiSen** [aalvarado/JiraDarkTheme#18]
The styling for sub-task is very bright and difficult to read

<img width="444" alt="Screenshot 2021-04-15 at 1 30 02 AM" src="https://user-images.githubusercontent.com/12984845/114771484-3e3a7c00-9d8a-11eb-9d5b-2a419e7e1514.png">

Thanks a lot for creating this

**Comment by aalvarado** [comment]
in which view is this?

**Comment by SubhrajyotiSen** [comment]
It is in the Project > Active Sprint > TODO/IN PROGRESS/IN REVIEW

**Comment by aalvarado** [comment]
I recently added an update that sets background color to subtasks, however I'm not able to get the issue id and title on top of the subtask.

**Comment by aalvarado** [comment]
Fixed on #21 

![image](https://user-images.githubusercontent.com/370322/116174869-22a56e80-a6c4-11eb-9d09-4a7c336f299f.png)
