### ISSUE TITLE
Pinned fields have white background

### ISSUE THREAD

**Issue by aalvarado** [aalvarado/JiraDarkTheme#27]
Same for Pinned fields:

<img width="450" alt="Screenshot 2021-04-22 at 11 52 30" src="https://user-images.githubusercontent.com/158600/115702764-3a49c380-a361-11eb-9152-937a54094417.png">

_Originally posted by @IanVaughan in https://github.com/aalvarado/JiraDarkTheme/issues/19#issuecomment-824738035_

**Comment by aalvarado** [comment]
Looks bad, feels bad. Hope to fix soon.

**Comment by brianbeergod** [comment]
I couldn't reproduce this, can the OP check to see if the other fixes released fixed this? I was able to pin but I didn't see it white.

**Comment by aalvarado** [comment]
I think it's safe to close since you confirmed it is now working and we can reopen if it's not :) thank you for checking!

**Comment by aalvarado** [comment]
fixed on #39
