### ISSUE TITLE
Labels on issues are hard to read

### ISSUE THREAD

**Issue by aalvarado** [aalvarado/JiraDarkTheme#33]
Some labels have a dark blue that makes it difficult to read.

**Comment by brianbeergod** [comment]
If you can show an example, I could take a swing at this one.

**Comment by aalvarado** [comment]
Definitely, I'll add examples soon. Thank you!

**Comment by jhracer3** [comment]
I have a similar/related issue, my labels are showing up with a very light background and light blue text, also making them hard to read.  Here's an example:

![image](https://user-images.githubusercontent.com/94385139/141812408-bf040ca9-46ad-4264-a92c-c68ded53ce01.png)

**Comment by jhracer3** [comment]
@brianbeergod example as requested :)

**Comment by aalvarado** [comment]
> I have a similar/related issue, my labels are showing up with a very light background and light blue text, also making them hard to read. Here's an example:
> 
> ![image](https://user-images.githubusercontent.com/94385139/141812408-bf040ca9-46ad-4264-a92c-c68ded53ce01.png)

Thank you. I had to create a new Jira account and try my theme there but there are different options on what to display on your project board.

**Comment by aalvarado** [comment]
some other areas that also need work:

![image](https://user-images.githubusercontent.com/370322/142239558-74d49d25-5f17-4da5-bd36-b7699b6dd677.png)

**Comment by aalvarado** [comment]
Here's the example for this particular issue:

![image](https://user-images.githubusercontent.com/370322/142239843-aab1adb8-c4b5-4b92-af79-08c71ceea26f.png)

**Comment by brianbeergod** [comment]
I think I have some of these solved. Let me test and I'll submit a PR.

**Comment by aalvarado** [comment]
should be solved in #38

**Comment by jhracer3** [comment]
awesome thank you!
