### ISSUE TITLE
Epic labels aren't showing up with gray bg in backlog view

### ISSUE THREAD

**Issue by brianbeergod** [aalvarado/JiraDarkTheme#35]
I noticed before I put this fix in that I couldn't see my labels due to a z-index issue. Adding this fixed it on mine, but I wanted to put it in here as an issue to have someone else test it before submitting it. 

`    .zd1ddu-13 {
        z-index: 2;
    }`

Before:
![before z-index](https://user-images.githubusercontent.com/42472382/140792506-eb0de71e-5ae2-4a75-9a4b-ed8573f502cc.png)

After:

![after z-index](https://user-images.githubusercontent.com/42472382/140792535-71216898-18ac-4275-a387-24355f32145f.png)

Not sure if you want me to submit a PR first, then test it, or if you want to test it before. Let me know!

**Comment by brianbeergod** [comment]
Actually realized the action/status drop down was hidden, too. 

Before:
![Status Before](https://user-images.githubusercontent.com/42472382/140794146-b001db61-7fd6-4fe8-9683-a32ad7bdaa3f.png)

After:
![Status After Z](https://user-images.githubusercontent.com/42472382/140794175-e64c80ef-974b-45eb-9748-7a6cff75cbf5.png)

Code:
`    .o8lyvj-0 {
        z-index: 2;
    }`

Would love help testing this as well.

**Comment by aalvarado** [comment]
Pr would be great

**Comment by aalvarado** [comment]
I think this is fixed in #36 ?

**Comment by aalvarado** [comment]
Please reopen if not. Thank you!
