### ISSUE TITLE
Plans button has a white square behind

### ISSUE THREAD

**Issue by aalvarado** [aalvarado/JiraDarkTheme#37]
![image](https://user-images.githubusercontent.com/370322/142240048-885c4b2a-ce6d-427b-a518-bfdaae4bf2e4.png)

**Comment by tayyab-razzaq** [comment]
You can fix this by adding the below code In your styles.

```
.OPuwm {
    background-color: #333 !important;
}
```

**Comment by dkniffin** [comment]
I think this is fixed now, per #50
