### ISSUE TITLE
`invert()` function is not recognized

### ISSUE THREAD

**Issue by Shelvak** [aalvarado/JiraDarkTheme#41]
Hi, importing the css I see this warning with `invert()` function. 

I'm using:
Jira Dark Gray1.13.4
Firefox 95.0.2 (64-bit)
Stylus 1.5.21

![imagen](https://user-images.githubusercontent.com/873323/148975754-4002bd98-2acd-401c-84b4-dfe3f9c9d384.png)

Cheers

**Comment by aalvarado** [comment]
Interesting, I'll look into this

**Comment by aalvarado** [comment]
seems all it needs is an amount to invert from, ie: `invert(1)` 

https://developer.mozilla.org/en-US/docs/Web/CSS/filter-function/invert()

**Comment by aalvarado** [comment]
fixed on 8caa964b01417e432ecba5477186722db8a5ae5b
