### ISSUE TITLE
Visual glitches in projects interface

### ISSUE THREAD

**Issue by aalvarado** [aalvarado/JiraDarkTheme#43]
reference url: https://jiradarktheme.atlassian.net/jira/software/c/projects/DARK/boards/1?selectedIssue=DARK-1
![image](https://user-images.githubusercontent.com/370322/161654624-b408d322-2edc-4813-a227-b04ae87d5d32.png)

**Comment by dkniffin** [comment]
These are fixed by https://github.com/aalvarado/JiraDarkTheme/pull/50
