### ISSUE TITLE
Visual glitches in issue view

### ISSUE THREAD

**Issue by aalvarado** [aalvarado/JiraDarkTheme#44]
Reference url:
https://jiradarktheme.atlassian.net/jira/software/c/projects/DARK/boards/1?modal=detail&selectedIssue=DARK-1

![image](https://user-images.githubusercontent.com/370322/161654833-292060de-e3aa-452c-91ce-c3b9da817745.png)

Hover:

![image](https://user-images.githubusercontent.com/370322/161654949-3e607bff-1cc4-462f-8a2a-b50b40382a65.png)

**Comment by Ningaro** [comment]
Click profile icon:
<img width="421" alt="image" src="https://user-images.githubusercontent.com/23503775/181816745-b220670b-8097-46e1-b55b-2b391851cd60.png">

Left navigate menu:
<img width="277" alt="image" src="https://user-images.githubusercontent.com/23503775/181816865-295fbaa2-5d1b-4aad-b550-910820bce603.png">

Hover on kanban column:
<img width="283" alt="image" src="https://user-images.githubusercontent.com/23503775/181817134-29be9baa-dd63-430c-9835-4b1ffedd79d5.png">

**Comment by dkniffin** [comment]
These are fixed by https://github.com/aalvarado/JiraDarkTheme/pull/50
