### ISSUE TITLE
Backgound color for flagged issues in backlog view

### ISSUE THREAD

**Issue by fiercedMonkey** [aalvarado/JiraDarkTheme#53]
The color scheme for flagged issues isn't well chosen. You can't read the text since it's a light grey on a white background

![image](https://user-images.githubusercontent.com/15922918/204918031-2f3a4e53-aee9-4951-b2ef-f5ca7f41491c.png)

**Comment by aalvarado** [comment]
would be very grateful for any prs here :)

**Comment by aalvarado** [comment]
Fixed by #54 and released on #55. Thanks @TeorikDeli
